#!/usr/bin/env python3
"""Extract ui-spec.json from a reference UI image.

Pipeline role:
Reference PNG -> measured JSON SSOT -> JUCE code generation.

The extractor is deterministic and intentionally conservative:
- canvas size is measured from the image
- palette is extracted with k-means when OpenCV is available
- optional knob hints can be supplied as x,y,r triples
- all coordinates are stored as both px and ratios
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
    import cv2  # type: ignore
    import numpy as np  # type: ignore
except Exception:  # pragma: no cover - fallback for machines without OpenCV
    cv2 = None
    np = None

from PIL import Image


def hex_rgba(rgb: tuple[int, int, int]) -> str:
    r, g, b = rgb
    return f"0xFF{r:02X}{g:02X}{b:02X}"


def ratio(value: float, total: float) -> float:
    return round(value / total, 6) if total else 0.0


def extract_palette(path: Path, count: int) -> dict[str, str]:
    img = Image.open(path).convert("RGB")
    img.thumbnail((256, 256))

    if cv2 is not None and np is not None:
        pixels = np.asarray(img).reshape((-1, 3)).astype("float32")
        criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 32, 0.2)
        _, labels, centers = cv2.kmeans(pixels, count, None, criteria, 3, cv2.KMEANS_PP_CENTERS)
        labels = labels.flatten()
        ranked = sorted(
            [(int((labels == i).sum()), tuple(int(v) for v in centers[i])) for i in range(len(centers))],
            reverse=True,
        )
        return {f"color_{i}": hex_rgba(rgb) for i, (_, rgb) in enumerate(ranked)}

    colors = img.getcolors(maxcolors=256 * 256) or []
    colors.sort(reverse=True, key=lambda item: item[0])
    return {f"color_{i}": hex_rgba(rgb) for i, (_, rgb) in enumerate(colors[:count])}


def parse_knob_hint(raw: str, canvas_w: int, canvas_h: int) -> tuple[str, dict[str, Any]]:
    # name:x,y,r or name:x,y,w,h
    name, values = raw.split(":", 1)
    parts = [float(p) for p in values.split(",")]
    if len(parts) == 3:
        cx, cy, radius = parts
        x = cx - radius
        y = cy - radius
        size = radius * 2.0
    elif len(parts) == 4:
        x, y, w, h = parts
        size = min(w, h)
        cx = x + size * 0.5
        cy = y + size * 0.5
        radius = size * 0.5
    else:
        raise ValueError("knob hint must be name:x,y,r or name:x,y,w,h")

    control = {
        "type": "image_knob",
        "bounds_px": {"x": round(x), "y": round(y), "w": round(size), "h": round(size)},
        "bounds_ratio": {
            "x": ratio(x, canvas_w),
            "y": ratio(y, canvas_h),
            "w": ratio(size, canvas_w),
            "h": ratio(size, canvas_h),
        },
        "center_px": {"x": round(cx), "y": round(cy)},
        "center_ratio": [ratio(cx, canvas_w), ratio(cy, canvas_h)],
        "radius_px": round(radius),
        "start_angle_degrees": -135,
        "end_angle_degrees": 135,
        "asset": "knob_base.png",
    }
    return name, control


def main() -> int:
    parser = argparse.ArgumentParser(description="Extract ui-spec.json from a reference image")
    parser.add_argument("reference", type=Path, help="Reference UI image")
    parser.add_argument("--out", type=Path, default=Path("ui/spec/ui-spec.json"))
    parser.add_argument("--palette-count", type=int, default=8)
    parser.add_argument("--knob", action="append", default=[], help="Knob hint: name:x,y,r or name:x,y,w,h")
    args = parser.parse_args()

    img = Image.open(args.reference).convert("RGB")
    canvas_w, canvas_h = img.size

    controls: dict[str, Any] = {}
    for hint in args.knob:
        name, control = parse_knob_hint(hint, canvas_w, canvas_h)
        controls[name] = control

    spec = {
        "$schema": "./ui-spec.schema.json",
        "canvas": {"width": canvas_w, "height": canvas_h},
        "reference": str(args.reference),
        "palette": extract_palette(args.reference, args.palette_count),
        "controls": controls,
        "tolerances": {"ui_diff_score_max": 0.025},
        "notes": "Generated by extract_ui_spec.py. Treat this JSON as the UI SSOT.",
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(spec, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
